In [1]:
import numpy as np


In [3]:
x = np.array([1,2,3,4,5,6,7])

In [5]:
print(x)

[1 2 3 4 5 6 7]


In [28]:
f = np.array([2,4,16])
z = np.array([11,10,9])
z[1]

10

In [7]:
print(f)
print(z)

[ 2  4 16]
[11 10  9]


In [10]:
f.dot(z)

206

In [21]:
x = np.array([1,2,4,5,7])
y = np.array([1,2,3,4])

In [22]:
print(x)
print(y)

[1 2 4 5 7]
[1 2 3 4]


In [23]:
x.dot(y)

ValueError: shapes (5,) and (4,) not aligned: 5 (dim 0) != 4 (dim 0)

In [24]:
p = np.array([1,2,4])
u = np.array([7,8,9])

In [25]:
p@u

59

In [26]:
np.dot(u,p)

59